### ISSUE TITLE
能否将其生成一个pdf或者epub的文件方便下载

### ISSUE THREAD

**Issue by dpzhang314** [perlatex/R_for_Data_Science#1]
能否将其生成一个pdf或者epub的文件方便下载，昨天试图将其pull下来，自己用
rstudio build ，折腾了一下午都没有成功，所以想提交一个issue给您，希望您在方便的时候生成一个。

**Comment by perlatex** [comment]
等dplyr1.0发布，代码重写后，会考虑生成pdf版本。
目前可以先 git clone 下来再运行
