### ISSUE TITLE
关于中文R语言书

### ISSUE THREAD

**Issue by YonghuiDong** [perlatex/R_for_Data_Science#12]
你好，

我自己使用R 已经超过十年了，偶然看到了你的这本书。翻了一下，非常喜欢。

全书整体性强，结构合理，逻辑清晰，语言简练，排版清新，图片设计尤其用心。这样的书籍在中文届太难得了。

所以特地来感谢一下。如果将来出版，我一定会买一本支持一下。

Dong

**Comment by perlatex** [comment]
感谢您的鼓励，但我不敢接受您这个标题，我修改了。关于中文书我推荐

- 黄湘云老师的《现代应用统计》 https://github.com/XiangyunHuang
- 张敬信老师的《R语言编程–基于tidyverse》https://github.com/zhjx19/
- 邓飞老师的《R语言进阶笔记》https://dengfei2013.gitee.io/r-language-advanced/
- 李东风老师的《R语言教程》https://www.math.pku.edu.cn/teachers/lidf/docs/Rbook/html/_Rbook/index.html

当然由于我的孤陋寡闻，更多的大牛书我还不知道。欢迎大家补充

**Comment by perlatex** [comment]
https://www.bigbookofr.com/index.html
https://r4ds.hadley.nz/index.html
https://bookdown.org/xiangyun/msg/
