### ISSUE TITLE
基础篇-第8章-8.5 更多部分的单词拼写似乎存在问题

### ISSUE THREAD

**Issue by JIAYI-CHANG** [perlatex/R_for_Data_Science#20]
本书"**基础篇-第8章-8.5 更多**"部分的英文单词拼写似乎存在问题，或许老师可以复查一下。

作为R语言初学者，从老师的书中学到了很多！感谢老师一直以来的付出与维护！

**Comment by perlatex** [comment]
感谢您的指出，已经修改了
