### ISSUE TITLE
部分建议

### ISSUE THREAD

**Issue by hope-data-science** [perlatex/R_for_Data_Science#28]
- 第2章链接<https://www.rstudio.com/download>失效。
- 第10章可重复性文档建议使用quarto进行讲解，或者进行补充，紧跟趋势。

**Comment by perlatex** [comment]
谢谢您的关注。
Rmarkdown感觉够用了，所以一直没去学quarto，
我很久没更新，
争取更新吧

**Comment by hope-data-science** [comment]
Rmd没问题，quarto大同小异。
链接更新一下吧，我让部分同学自学，结果很多同学反馈Rstudio这个链接打不开。
实在写的很好，比市面任何R入门教程都强。

**Comment by perlatex** [comment]
感谢您的鼓励，现在链接已经更新。
