### ISSUE TITLE
- Inf 介绍时勘误

### ISSUE THREAD

**Issue by yiorfun** [perlatex/R_for_Data_Science#35]
baseR_operators.Rmd, line 267

- `Inf`，是**Infinity**的简写，表示无限大；`-Inf`表示无限小，比如我们用1除以0

此处 `- Inf` 应该表示负无穷大，因为：

(1) - Inf < 0 返回值 TRUE
(2) 1 / 0 返回值 Inf
(3) - 1 / 0 返回值 - Inf
(4) abs(- Inf) 返回值 Inf

我用的版本是

$version.string
[1] "R version 4.3.2 (2023-10-31 ucrt)"

非常感谢您的付出和辛劳，非常棒的一部R教程。

**Comment by perlatex** [comment]
感谢您的勘误，我这里确实写错了， Inf 应该是“无穷大”的意思。
感谢您的关注和鼓励。
