### ISSUE TITLE
为何不能做成jupyter notebook的形式

### ISSUE THREAD

**Issue by A-Pai** [perlatex/R_for_Data_Science#5]
课件做的很好，当时rmd文件运行起来还是没有jupyter notebook运行的那么漂亮，王老师，可否做成jupyter notebook的形式

**Comment by perlatex** [comment]
我对jupyter notebook不熟啊

**Comment by A-Pai** [comment]
> 我对jupyter notebook不熟啊

这是jupyter notebook运行的截图，优点是：可作为课件，边看边运行，用于提示的文字部分直接显示为不同格式，这些Rmarkdown似乎不行
![image](https://user-images.githubusercontent.com/5112397/113237447-6da4af80-92d9-11eb-8240-ed6fa82560a0.png)
