### ISSUE TITLE
str_c可以被paste替代？

### ISSUE THREAD

**Issue by A-Pai** [perlatex/R_for_Data_Science#7]
https://bookdown.org/wangminjie/R4DS/stringr.html#字符串组合
![image](https://user-images.githubusercontent.com/5112397/113236896-64671300-92d8-11eb-9224-28528186be09.png)
str_c可以被paste替代？大神既然新创造了这个函数，是不是有独特的用途？

**Comment by perlatex** [comment]
``` r
library(stringr)
str_c(c("a", NA_character_, "c"), c("1", "2", "3", "4"))
#> Warning in stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE):
#> longer object length is not a multiple of shorter object length
#> [1] "a1" NA   "c3" "a4"


paste0(c("a", NA_character_, "c"), c("1", "2", "3", "4"))
#> [1] "a1"  "NA2" "c3"  "a4"
```

<sup>Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

stringr::str_c() 设计更安全些

**Comment by A-Pai** [comment]
> ```r
> library(stringr)
> str_c(c("a", NA_character_, "c"), c("1", "2", "3", "4"))
> #> Warning in stri_c(..., sep = sep, collapse = collapse, ignore_null = TRUE):
> #> longer object length is not a multiple of shorter object length
> #> [1] "a1" NA   "c3" "a4"
> 
> 
> paste0(c("a", NA_character_, "c"), c("1", "2", "3", "4"))
> #> [1] "a1"  "NA2" "c3"  "a4"
> ```
> 
> Created on 2021-04-12 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)
> 
> stringr::str_c() 设计更安全些

----更安全指的是什么？

**Comment by perlatex** [comment]
安全性指的是，缺失值的处理、向量长度不是整数倍时有警告提醒以及速度提升等等

**Comment by A-Pai** [comment]
明白了，谢谢，可以写一个有对比效果的例子吗？
