### ISSUE TITLE
Potential typo in the proportional odds model

### ISSUE THREAD

**Issue by huanfachen** [perlatex/R_for_Data_Science#8]
There is a potential typo in the proportional odds model in Chapter 40. The formula in the `polr` function of the `MASS` library is:

logit(P(Y≤j))=αj - β1 * x1 - β2 * x2

So, when interpreting the result of the following function, the sign of beta should be reversed. For example, the coefficient of `edu_m` should be -0.461 in the equation. 

```R
polr(formula = edu ~ edu_f + edu_m + sex + num_siblings + urban, 
##     data = df1, method = c("logistic"))
```

References on the formula of `polr`:
- See documentation on `polr`
- Venables, W.N. and Ripley, B.D. (2003) Modern Applied Statistics with S, Fourth. Springer, New York

**Comment by perlatex** [comment]
非常感谢您@huanfachen 指出我的错误，我需要再看下您的文档，争取在下次更新时修正。
