### ISSUE TITLE
有些函数过时了，要是能换成最新的就更好了

### ISSUE THREAD

**Issue by s609078902** [perlatex/R_for_Data_Science#9]
有个朋友想入门R语言，我推荐了这本书给她。粗略看下来是这本书非常棒，对新手十分友好，是一本很适合用来入门的书，更难得的是作者有随着tidyverse包的迭代同步更新着本书。个人觉得，对于 `top_n()`、`summarise_if` 等已经被代替的函数，没有必要专门去学习了，可以在解释为什么要引入 `across()` 函数时作为补充说明，就如书中 **across() 之美**的部分那样。当然，可能作者从教学上有所考量才选择保留这些内容，为我的无理提前说一声抱歉。

**Comment by perlatex** [comment]
谢谢你的关注和建议，今后课件的中我会尽可能用成熟稳定的函数，让新手也能感受到 Tidyverse 的友好。
